# fly.toml app configuration file generated for elevenlabs-auth-api on 2025-08-12T11:35:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "elevenlabs-auth-api"
primary_region = "sin"

[build]

[env]
  DATABASE_TYPE = "supabase"
  SUPABASE_URL = "https://wjkejklrtrhubbljfrdz.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqa2Vqa2xydHJodWJibGpmcmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjQyNjAsImV4cCI6MjA3MDU0MDI2MH0.M8iaT_F2nk_HpnjXh0gdiKwFGb8ed3z1RU0myWSK4kg"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[machine]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
